pipeline{
    agent any
    stages{
        stage("Build Frontend"){
            steps{
                checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/CristobalTorresU/Tingeso-Evaluacion-1']])
                dir("AutoFixFrontEnd"){
                    sh "npm install"
                    sh "npm run build"
                }
            }
        }
        stage("Build and Push Docker Image"){
            steps{
                dir("AutoFixFrontEnd"){
                    script{
                         withDockerRegistry(credentialsId: 'docker-credentials'){
                            sh "docker build -t dilget/autofix-frontend ."
                            sh "docker push dilget/autofix-frontend"
                        }
                    }                    
                }
            }
        }
    }
}